# Generated by Django 6.1 on 2026-08-21 05:14

import core.validators
import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('country', django_countries.fields.CountryField(default='US', max_length=2, verbose_name='Country')),
                ('first_name', models.CharField(max_length=100, validators=[core.validators.validate_first_name], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, validators=[core.validators.validate_last_name], verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=16, null=True, region=None, unique=True, verbose_name='Phone Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Enabled')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'account_user',
                'constraints': [models.CheckConstraint(condition=models.Q(('email__isnull', False), ('phone_number__isnull', False), ('is_staff', True), _connector='OR'), name='user_requires_contact_unless_staff')],
            },
        ),
    ]
