# Generated by Django 6.1 on 2026-08-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
