# Generated by Django 6.1 on 2026-08-23 08:03

import core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[core.validators.validate_first_name], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[core.validators.validate_last_name], verbose_name='Last Name'),
        ),
    ]
