# Generated by Django 6.1 on 2026-08-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accountuser_country_alter_accountuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accountuser',
            name='user_requires_contact_unless_staff',
        ),
    ]
