# Generated by Django 6.1 on 2026-08-25 22:37

import core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_accountuser_user_requires_contact_unless_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='first_name',
            field=models.CharField(max_length=100, validators=[core.validators.validate_first_name], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='last_name',
            field=models.CharField(max_length=100, validators=[core.validators.validate_last_name], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[core.validators.validate_phone_number], verbose_name='Phone Number'),
        ),
    ]
