# Generated by Django 6.1 on 2026-08-21 05:14

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import timezone_field.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('country', django_countries.fields.CountryField(default='US', max_length=2, verbose_name='Country')),
                ('name', models.CharField(max_length=255, verbose_name='Business Name')),
                ('industry', models.CharField(max_length=255, verbose_name='Industry')),
                ('email', models.EmailField(max_length=254, verbose_name='Business Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=16, region=None, verbose_name='Business Phone Number')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('logo', models.URLField(blank=True, verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'db_table': 'business',
            },
        ),
        migrations.CreateModel(
            name='BusinessItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('unavailable', 'Unavailable'), ('discontinued', 'Discontinued')], default='draft', max_length=25, verbose_name='Status')),
                ('discontinued_date', models.DateTimeField(blank=True, null=True, verbose_name='Discontinued Date')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Business Item',
                'verbose_name_plural': 'Business Items',
                'db_table': 'business_item',
            },
        ),
        migrations.CreateModel(
            name='BusinessLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=255, verbose_name='Location Name')),
                ('address_line_1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state_region', models.CharField(max_length=100, verbose_name='State/Region')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal Code')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('timezone', timezone_field.fields.TimeZoneField(verbose_name='Time Zone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Business Location',
                'verbose_name_plural': 'Business Locations',
                'db_table': 'business_location',
            },
        ),
        migrations.CreateModel(
            name='BusinessStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('email', models.EmailField(max_length=254, verbose_name='Staff Email')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], max_length=20, verbose_name='Role')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='pending', max_length=25, verbose_name='Status')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Staff',
                'verbose_name_plural': 'Business Staff',
                'db_table': 'business_staff',
                'constraints': [models.UniqueConstraint(fields=('business', 'user'), name='unique_business_user'), models.UniqueConstraint(fields=('business', 'email'), name='unique_business_staff_email')],
            },
        ),
    ]
