# Generated by Django 6.1 on 2026-08-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='country',
        ),
    ]
