# Generated by Django 6.1 on 2026-08-19 20:54

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2, verbose_name='Country'),
        ),
    ]
