# Generated by Django 6.1 on 2026-08-25 22:40

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[core.validators.validate_phone_number], verbose_name='Business Phone Number'),
        ),
    ]
