# Generated by Django 6.1 on 2026-08-21 05:14

import apps.backoffice.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[apps.backoffice.validators.validate_platform_admin_email], verbose_name='Admin Email')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('support', 'Support')], max_length=20, verbose_name='Role')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='pending', max_length=25, verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='platform_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Admin',
                'verbose_name_plural': 'Platform Admins',
                'db_table': 'platform_admin',
            },
        ),
    ]
