# Generated by Django 6.1 on 2026-08-21 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backoffice', '0001_initial'),
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardProgramType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Reward Program Type',
                'verbose_name_plural': 'Reward Program Types',
                'db_table': 'reward_program_type',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('reward_type', models.CharField(choices=[('discount_amount', 'Discount Amount'), ('discount_percentage', 'Discount Percentage'), ('free_item', 'Free Item')], max_length=25, verbose_name='Reward Type')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Description')),
                ('amount_required', models.PositiveIntegerField(verbose_name='Amount Required')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount Amount')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount Percentage')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='draft', max_length=25, verbose_name='Status')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('earned_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='earned_rewards', to='businesses.businessitem')),
                ('qualifying_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qualifying_rewards', to='businesses.businessitem')),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Rewards',
                'db_table': 'reward',
            },
        ),
        migrations.CreateModel(
            name='RewardProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='draft', max_length=25, verbose_name='Status')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reward_programs', to='businesses.business')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reward_programs', to='rewards.rewardprogramtype')),
            ],
            options={
                'verbose_name': 'Reward Program',
                'verbose_name_plural': 'Reward Programs',
                'db_table': 'reward_program',
            },
        ),
        migrations.CreateModel(
            name='RewardEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('receipt_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Receipt Number')),
                ('receipt_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Receipt Total')),
                ('amount_earned', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Amount Earned')),
                ('granted_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='earned_rewards', to='businesses.businessstaff')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earned_rewards', to='businesses.businesslocation')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='earned_rewards', to='rewards.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earned_rewards', to=settings.AUTH_USER_MODEL)),
                ('reward_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earned_rewards', to='rewards.rewardprogram')),
            ],
            options={
                'verbose_name': 'Reward Earning',
                'verbose_name_plural': 'Reward Earnings',
                'db_table': 'reward_earning',
            },
        ),
        migrations.CreateModel(
            name='RewardAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('adjustment_type', models.CharField(choices=[('other', 'Other')], max_length=50, verbose_name='Adjustment Type')),
                ('reason', models.TextField(blank=True, max_length=255, verbose_name='Reason')),
                ('adjustment_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Amount Adjusted')),
                ('adjusted_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjusted_rewards', to='backoffice.platformadmin')),
                ('adjusted_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjusted_rewards', to='businesses.businessstaff')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_rewards', to='businesses.businesslocation')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjusted_rewards', to='rewards.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjusted_rewards', to=settings.AUTH_USER_MODEL)),
                ('reward_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjusted_rewards', to='rewards.rewardprogram')),
            ],
            options={
                'verbose_name': 'Reward Adjustment',
                'verbose_name_plural': 'Reward Adjustments',
                'db_table': 'reward_adjustment',
            },
        ),
        migrations.AddField(
            model_name='reward',
            name='reward_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rewards', to='rewards.rewardprogram'),
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('amount_redeemed', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Amount Redeemed')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_rewards', to='businesses.businesslocation')),
                ('processed_by_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redeemed_rewards', to='businesses.businessstaff')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redeemed_rewards', to='rewards.reward')),
                ('reward_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redeemed_rewards', to='rewards.rewardprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redeemed_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reward Redemption',
                'verbose_name_plural': 'Reward Redemptions',
                'db_table': 'reward_redemption',
            },
        ),
        migrations.CreateModel(
            name='RewardLocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_locations', to='businesses.businesslocation')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_locations', to='rewards.reward')),
            ],
            options={
                'verbose_name': 'Participating Reward Location',
                'verbose_name_plural': 'Participating Reward Locations',
                'db_table': 'reward_location',
                'constraints': [models.UniqueConstraint(fields=('reward', 'location'), name='unique_reward_location')],
            },
        ),
        migrations.CreateModel(
            name='RewardProgramLocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reward_program_locations', to='businesses.businesslocation')),
                ('reward_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_locations', to='rewards.rewardprogram')),
            ],
            options={
                'verbose_name': 'Participating Reward Program Location',
                'verbose_name_plural': 'Participating Reward Program Locations',
                'db_table': 'reward_program_location',
                'constraints': [models.UniqueConstraint(fields=('reward_program', 'location'), name='unique_reward_program_location')],
            },
        ),
    ]
