# Generated by Django 6.1 on 2026-08-21 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardredemption',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redeemed_rewards', to='businesses.businesslocation'),
        ),
    ]
