# Generated by Django 6.1 on 2026-08-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_rewardprogramtype_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardprogramtype',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),
    ]
