# Generated by Django 6.1 on 2026-08-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_rewardprogramlocation_modified_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewardlocation',
            options={'verbose_name': 'Participating Reward Location', 'verbose_name_plural': 'Participating Reward Locations'},
        ),
        migrations.AlterModelOptions(
            name='rewardprogramlocation',
            options={'verbose_name': 'Participating Reward Program Location', 'verbose_name_plural': 'Participating Reward Program Locations'},
        ),
        migrations.AddField(
            model_name='rewardlocation',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),
    ]
