# Generated by Django 6.1 on 2026-08-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_alter_rewardlocation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardadjustment',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),
        migrations.AddField(
            model_name='rewardearning',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),
    ]
