name: CI

on:
  push:
  #   branches: [ "main" ]
  pull_request:
  #   branches: [ "main" ]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest

    # defaults:
    #   run:
    #     working-directory: ./server

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: wewards_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_NAME: wewards_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          working-directory: client
          build: npm run build
          start: npm run dev
          browser: chrome

      - name: Install dependencies
        working-directory: ./server
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Models Tests
        working-directory: ./server
        run: |
          python manage.py test tests.test_models

      - name: Run URL Tests
        working-directory: ./server
        run: |
          python manage.py test tests.test_urls

      - name: Run Views Tests
        working-directory: ./server
        run: |
          python manage.py test tests.test_views